ahonymous_blog:
    resource: "@AhonymousBlogBundle/Resources/config/routing.yml"

ahonymous_fos_user:
    resource: "@AhonymousUserBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: en|ru|uk

ahonymous_guest:
    resource: "@AhonymousGuestBundle/Resources/config/routing.yml"
    prefix: /{_locale}/guest
    requirements:
        _locale: en|ru|uk
