_hello:
    resource: "@AhonymousBlogBundle/Controller/"
    type:     annotation
    prefix:   /

_article:
        resource: "@AhonymousBlogBundle/Resources/config/routing/article.yml"
        prefix:   /article

_category:
        resource: "@AhonymousBlogBundle/Resources/config/routing/category.yml"
        prefix:   /category

