_hello:
    resource: "@AhonymousBlogBundle/Controller/"
    type:     annotation
    prefix:   /

_author:
        resource: "@AhonymousBlogBundle/Resources/config/routing/author.yml"
        prefix:   /author

_article:
        resource: "@AhonymousBlogBundle/Resources/config/routing/article.yml"
        prefix:   /article

_category:
        resource: "@AhonymousBlogBundle/Resources/config/routing/category.yml"
        prefix:   /category

_comment:
        resource: "@AhonymousBlogBundle/Resources/config/routing/comment.yml"
        prefix:   /comment

