home:
    pattern:  /{page}
    defaults: { _controller: "AhonymousBlogBundle:Default:index", _locale: en, page: 1 }
    requirements:
        page:  \d+

about:
    pattern:  /about
    defaults: { _controller: "AhonymousBlogBundle:Default:about", _locale: en }

_search:
    pattern:  /search
    defaults: { _controller: "AhonymousBlogBundle:Default:search", _locale: en }

_find:
    pattern:  /find/{searched}/{page}
    defaults: { _controller: "AhonymousBlogBundle:Default:find", _locale: en, searched: '', page: 1 }
    requirements:
        page:  \d+

_article:
    resource: "@AhonymousBlogBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

_category:
    resource: "@AhonymousBlogBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

article_show:
    pattern:  /article/{slug}
    defaults: { _controller: "AhonymousBlogBundle:Article:show" }

category_show:
    pattern:  /{slug}/show
    defaults: { _controller: "AhonymousBlogBundle:Category:show" }
