fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#fos_user_security_login:
#    pattern:  /{_locale}/login
#    defaults: { _controller: "FOSUserBundle:Security:login", _locale: en }
#    requirements:
#        _locale: en|ru|uk
#
#fos_user_security_check:
#    pattern:  /login_check
#    defaults: { _controller: "FOSUserBundle:Security:check" }
#    requirements:
#        _method: POST
#
#fos_user_security_logout:
#    pattern:  /logout
#    defaults: { _controller: "FOSUserBundle:Security:logout" }
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /{_locale}/profile
#    requirements:
#        _locale: en|ru|uk
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /{_locale}/register
#    requirements:
#        _locale: en|ru|uk
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /{_locale}/profile
#    requirements:
#        _locale: en|ru|uk
