<?php

namespace Ahonymous\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllArticles()
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT a FROM AhonymousBlogBundle:Article a ORDER BY a.created, a.id DESC');

        return $query;
    }

    public function findLastName($limit = 5)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT a.name, a.slug FROM AhonymousBlogBundle:Article a ORDER BY a.updated DESC')
            ->setMaxResults($limit)
        ;

        return $query;
    }
}
