article:
    pattern:  /
    defaults: { _controller: "AhonymousBlogBundle:Article:index" }

article_new:
    pattern:  /new
    defaults: { _controller: "AhonymousBlogBundle:Article:new" }

article_create:
    pattern:  /create
    defaults: { _controller: "AhonymousBlogBundle:Article:create" }
    requirements: { _method: post }

article_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "AhonymousBlogBundle:Article:edit" }

article_update:
    pattern:  /{slug}/update
    defaults: { _controller: "AhonymousBlogBundle:Article:update" }
    requirements: { _method: post|put }

article_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: "AhonymousBlogBundle:Article:delete" }
    requirements: { _method: post|delete }
