author:
    pattern:  /
    defaults: { _controller: "AhonymousBlogBundle:Author:index" }

author_show:
    pattern:  /{id}/show
    defaults: { _controller: "AhonymousBlogBundle:Author:show" }

author_new:
    pattern:  /new
    defaults: { _controller: "AhonymousBlogBundle:Author:new" }

author_create:
    pattern:  /create
    defaults: { _controller: "AhonymousBlogBundle:Author:create" }
    requirements: { _method: post }

author_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AhonymousBlogBundle:Author:edit" }

author_update:
    pattern:  /{id}/update
    defaults: { _controller: "AhonymousBlogBundle:Author:update" }
    requirements: { _method: post|put }

author_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AhonymousBlogBundle:Author:delete" }
    requirements: { _method: post|delete }
