category:
    pattern:  /
    defaults: { _controller: "AhonymousBlogBundle:Category:index" }

category_show:
    pattern:  /{slug}/show
    defaults: { _controller: "AhonymousBlogBundle:Category:show" }

category_new:
    pattern:  /new
    defaults: { _controller: "AhonymousBlogBundle:Category:new" }

category_create:
    pattern:  /create
    defaults: { _controller: "AhonymousBlogBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "AhonymousBlogBundle:Category:edit" }

category_update:
    pattern:  /{slug}/update
    defaults: { _controller: "AhonymousBlogBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: "AhonymousBlogBundle:Category:delete" }
    requirements: { _method: post|delete }
